#!/bin/bash
//Ubuntu Terminal commands https://www.geeksforgeeks.org/how-to-create-a-shell-script-in-linux/#
sudo apt-get update
sudo apt-get install -y build-essential linux-headers-$(uname -r)
sudo apt-get install virtualbox-guest-utils
sudo adduser $(whoami) vboxsf
